### ISSUE TITLE
RTP and NAT issue

### ISSUE THREAD

**Issue by quangvnm** [OpenLI-NZ/openli#26]
Hello,

Firstly, We 'd like to thank you for this awesome project.
We had encountered a weird issue with SIP client behind NAT.

### Issue:
We found that there is no RTP stream captured and sent to mediator

### Context
- All SIP clients (Linphone application on iOS/Android) is behind home router, work office or mobile operator's gateway and has private IP address.
- The SIP server is in public, no nat. And the OpenLI is setup to listen on a dummy interface which has mirrored traffic from SIP servers.

### Analyze
After digging into the code we found out that the matching of RTP stream with IP source/destination has some problems.

Firstly, the RTP stream is associated with one or two address IP (targetaddr and otheraddr in code), corresponding to two endpoints/peers of RTP stream.

The address is taken from `get_sip_media_ipaddr`, e.g:
https://github.com/wanduow/openli/blob/fb3f13937c7914dbb092bb63cf09cbcbb20f404c/src/collector/collector_sync_voip.c#L602-L607

When I read the code of `get_sip_media_ipaddr`, the ip string is taken from "c" field in SIP/SDP protocol, so it could be a private address and then be used to associated to thisrtp stream.

And then later, when trying to find if a particular sock belong to the that particular rtp stream:
https://github.com/wanduow/openli/blob/8dc9dcb76a2cc09b1682dff4bb8e89ddd8ad915e/src/collector/ipmmcc.c#L92-L119

The ipa and ipb is taken directly from IP header of RTP packet, so they are public addresses
So there isn't any match because RTP stream 's target addr or other addr is private address. So the RTP packet is thrown away.

### A "dirty" fix
If we tried to patch the line with `get_sip_media_ipaddr` which will return public IP, the problem is solved and we could see the RTP stream after mediator but we are not sure if this is the elegant way of doing so?

**Comment by salcock** [comment]
Hi,

Thanks for your detailed description of the issue.

Yes, you are correct -- an OpenLI collector that is seeing SIP traffic from one side of a NAT and RTP traffic from the other side is going to have some problems recognising the RTP stream as belonging to the original SIP session.

This wasn't a situation I originally anticipated -- the code was originally written with the expectation that ISPs would run the collectors within their internal networks rather than expecting their SIP clients (and therefore the providers of those SIP clients) to do the interception for them :)

In that case, I'm wondering if there is some value in OpenLI providing a configurable "NAT" mode for VOIP intercepts which, if enabled, does more or less what you propose as a fix. It would need to be able to determine the "public" and "private" IP for the host that the collector is running on and substitute in the "public" one for the "private" one if the private one is returned by `get_sip_media_ipaddr`.

If you were to make a patch to implement your "dirty" fix and have it work in your use case, I would be very grateful if you could send it through. I can try to turn it into a more generic solution like what I described above.

**Comment by quangvnm** [comment]
Ah ha, thank you @salcock :)

I've just tried to integrate OpenLI with Asterisk, and I know about the option of comedia (Connection-Oriented Media), where SIP server will wait for connection to UDP port specified in SIP server's 200 OK response before trying to connect to that client over RTP.

So I think we could guess and match the RTP connection by UDP port on OpenLI/SIP server, defined in SIP/SDP 200 OK?

Btw, we got lucky that the NAT port is the same for private and public address. But I guess in normal case of NAT, the port could be totally different, so we should also patch the get_sip_media_port too, shouldn't we?

At the moment, we took the IP address from irimsg, but it has only the IP address, not port number. So it is not perfect.

When I take a look at tracepktdump, we have IP address and port number of interceptor, and it is take from IP header of that SIP message, could we extract these IP and port for RTP matching?

Btw, I found another bug (or feature) where two targets call each other, there is only 1 intercepted stream, because the call has the same call-id, so the create_new_voip_session is only called once, instead of two, though there might be the case of two LI agents listen to two differents targets, isn't it?
Is it the case you originally anticipated, should I file another bug report? :)

**Comment by salcock** [comment]
I would need to see a pcap or two of SIP using connection-oriented media and the subsequent RTP flows before making any comment on whether extracting the port from the 200 OK would be likely to work.

I'm learning a lot about VOIP as this project progresses and I've found that the easiest (only?) way to learn more by working through actual examples of the packets that appear on the wire. Every vendor does things slightly differently, so I'm finding that I have to collect a lot of sample pcaps of SIP traffic from many different sources :)

The last bug you mention is definitely a bug -- I've had some similar reports recently, so I will try to make sure that is fixed before the next release.
